# Memory-efficient GAT Configuration

data:
  similarity_pt_path: "/work/hdd/bdau/mbanisharifdehkordi/GNN_4_IO_5/data/100K/similarity_output_0.75/similarity_graph_20250812_002240.pt"
  similarity_npz_path: "/work/hdd/bdau/mbanisharifdehkordi/GNN_4_IO_5/data/100K/similarity_output_0.75/similarity_graph_20250812_002240.npz"
  features_csv_path: "/work/hdd/bdau/mbanisharifdehkordi/GNN_4_IO_5/data/100K/aiio_sample_100000_normalized.csv"
  root: "./data/processed"
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  stratify: true

model:
  type: "standard"
  hidden_channels: 256
  num_layers: 3
  heads: [8, 4, 1]
  dropout: 0.15
  edge_dim: 1
  residual: true
  layer_norm: true
  feature_augmentation: false  # Turn off to save memory
  pool_type: "mean"

training:
  epochs: 200
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adamw"
  scheduler: "cosine"
  gradient_clip: 1.0
  early_stopping_patience: 40
  batch_size: 1024
  num_neighbors: [15, 10]
  accumulation_steps: 2
  mixed_precision: false

experiment:
  seed: 42
  save_dir: "./experiments/gat_baseline"
  use_wandb: false
  project_name: "io_performance_gnn"
  run_name: "gat_memory_efficient"